# Настройка сервера
server:
  # Указываем номер порта
  port: 8085
  # Указываем путь корневого контекста
  servlet:
    context-path: /api

# Настройка Spring
spring:
  # Настройка JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_default: false
  # Настройка источника данных
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tyk?currentSchema=tyk_schema
    username: tyk
    password: tykpass
  # Настройка миграция для FlyWay
  flyway:
    locations: classpath:db/migration
    sql-migration-separator: _
    sql-migration-suffixes: .sql
